name: Testing

on:
  workflow_call:
    inputs:
      minimum-php:
        description: 'Minimum PHP version to test against.'
        type: string
        required: false
        default: '7.2'
      minimum-wp:
        description: 'Minimum WP version to test against.'
        type: string
        required: false
        default: '4.9'
      with-coverage:
        description: 'Include coverages tests.'
        type: boolean
        required: false
        default: true
      matrix:
        description: 'Additional matrix entries to include or exclude.'
        type: string
        required: false
        default: '{ "include": [], "exclude": [] }'

permissions:
  contents: read

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-matrix:
    name: Get base test matrix
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.base-matrix.outputs.matrix }}
    steps:
    - name: Set matrix
      id: base-matrix
      env:
        ADDITIONAL_MATRIX: ${{ inputs.matrix }}
      run: |
        MATRIX=$(cat << EOF
        {
          "include": [
            {
              "php": "7.2",
              "wp": "4.9",
              "mysql": "mysql-5.6"
            },
            {
              "php": "7.2",
              "wp": "latest",
              "mysql": "mysql-8.0"
            },
            {
              "php": "7.2",
              "wp": "latest",
              "dbtype": "sqlite"
            },
            {
              "php": "7.3",
              "wp": "latest",
              "mysql": "mysql-8.0"
            },
            {
              "php": "7.3",
              "wp": "latest",
              "dbtype": "sqlite"
            },
            {
              "php": "7.4",
              "wp": "latest",
              "mysql": "mysql-8.0"
            },
            {
              "php": "7.4",
              "wp": "latest",
              "dbtype": "sqlite"
            },
            {
              "php": "8.0",
              "wp": "latest",
              "mysql": "mysql-8.0"
            },
            {
              "php": "8.0",
              "wp": "latest",
              "dbtype": "sqlite"
            },
            {
              "php": "8.1",
              "wp": "latest",
              "mysql": "mysql-8.0"
            },
            {
              "php": "8.1",
              "wp": "latest",
              "dbtype": "sqlite"
            },
            {
              "php": "8.2",
              "wp": "latest",
              "mysql": "mysql-8.0"
            },
            {
              "php": "8.2",
              "wp": "latest",
              "dbtype": "sqlite"
            },
            {
              "php": "8.3",
              "wp": "latest",
              "mysql": "mysql-8.0"
            },
            {
              "php": "8.3",
              "wp": "latest",
              "mysql": "mysql-8.4"
            },
            {
              "php": "8.3",
              "wp": "latest",
              "dbtype": "sqlite"
            },
            {
              "php": "8.3",
              "wp": "latest",
              "mysql": "mariadb-11.4",
              "dbtype": "mariadb"
            },
            {
              "php": "8.4",
              "wp": "latest",
              "mysql": "mysql-8.0"
            },
            {
              "php": "8.4",
              "wp": "latest",
              "mysql": "mysql-8.4"
            },
            {
              "php": "8.4",
              "wp": "latest",
              "dbtype": "sqlite"
            },
            {
              "php": "8.4",
              "wp": "latest",
              "mysql": "mariadb-11.4",
              "dbtype": "mariadb"
            },
            {
              "php": "8.5",
              "wp": "latest",
              "mysql": "mysql-8.0",
              "coverage": true
            },
            {
              "php": "8.5",
              "wp": "latest",
              "mysql": "mysql-8.4"
            },
            {
              "php": "8.5",
              "wp": "latest",
              "dbtype": "sqlite"
            },
            {
              "php": "8.5",
              "wp": "latest",
              "mysql": "mariadb-11.4",
              "dbtype": "mariadb"
            },
            {
              "php": "7.4",
              "wp": "trunk",
              "mysql": "mysql-8.0"
            },
            {
              "php": "7.4",
              "wp": "trunk",
              "mysql": "mysql-5.7"
            },
            {
              "php": "7.4",
              "wp": "trunk",
              "mysql": "mysql-5.6"
            },
            {
              "php": "7.4",
              "wp": "trunk",
              "mysql": "mysql-8.0"
            },
            {
              "php": "8.0",
              "wp": "trunk",
              "mysql": "mysql-8.0"
            },
            {
              "php": "8.0",
              "wp": "trunk",
              "mysql": "mysql-5.7"
            },
            {
              "php": "8.0",
              "wp": "trunk",
              "mysql": "mysql-5.6"
            },
            {
              "php": "8.1",
              "wp": "trunk",
              "mysql": "mysql-8.0"
            },
            {
              "php": "8.2",
              "wp": "trunk",
              "mysql": "mysql-8.0"
            },
            {
              "php": "8.3",
              "wp": "trunk",
              "mysql": "mysql-8.0"
            },
            {
              "php": "8.3",
              "wp": "trunk",
              "mysql": "mysql-8.4"
            },
            {
              "php": "8.3",
              "wp": "trunk",
              "dbtype": "sqlite"
            },
            {
              "php": "8.3",
              "wp": "trunk",
              "mysql": "mariadb-11.4",
              "dbtype": "mariadb"
            },
            {
              "php": "8.4",
              "wp": "trunk",
              "mysql": "mysql-8.0"
            },
            {
              "php": "8.4",
              "wp": "trunk",
              "mysql": "mysql-8.4"
            },
            {
              "php": "8.4",
              "wp": "trunk",
              "dbtype": "sqlite"
            },
            {
              "php": "8.4",
              "wp": "trunk",
              "mysql": "mariadb-11.4",
              "dbtype": "mariadb"
            },
            {
              "php": "8.5",
              "wp": "trunk",
              "mysql": "mysql-8.0"
            },
            {
              "php": "8.5",
              "wp": "trunk",
              "mysql": "mysql-8.4"
            },
            {
              "php": "8.5",
              "wp": "trunk",
              "dbtype": "sqlite"
            },
            {
              "php": "8.5",
              "wp": "trunk",
              "mysql": "mariadb-11.4",
              "dbtype": "mariadb"
            },
            {
              "php": "nightly",
              "wp": "trunk",
              "mysql": "mysql-8.4"
            },
            {
              "php": "nightly",
              "wp": "trunk",
              "dbtype": "sqlite"
            },
            {
              "php": "8.5",
              "wp": "latest",
              "dbtype": "sqlite",
              "object_cache": "sqlite"
            },
            {
              "php": "8.5",
              "wp": "trunk",
              "dbtype": "sqlite",
              "object_cache": "sqlite"
            },
            {
              "php": "8.5",
              "wp": "trunk",
              "dbtype": "sqlite",
              "os": "macos-latest"
            },
            {
              "php": "8.5",
              "wp": "trunk",
              "dbtype": "sqlite",
              "os": "windows-latest"
            }
          ]
        }
        EOF
        )
        MERGED_MATRIX=$(echo "$MATRIX" "$ADDITIONAL_MATRIX" | jq -s '
          . as $root |
          (($root[0].exclude // []) + ($root[1].exclude // [])) as $excludes |
          {
            include: (
              (.[0].include + .[1].include | map(if .os == null then .os = "" else . end)) |
              map(. as $item | select($excludes | any(. as $rule | all($rule|keys[]; $item[.] == $rule[.])) | not)) |
              unique
            )
          }
        ')
        echo matrix=$MERGED_MATRIX >> $GITHUB_OUTPUT

  prepare-unit:
    name: Prepare matrix for unit tests
    needs: get-matrix
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Check out source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Check existence of composer.json & phpunit.xml.dist files
        id: check_files
        run: echo "files_exists=$([ -f composer.json ] && [ -f phpunit.xml.dist ] && echo true || echo false)" >> "$GITHUB_OUTPUT"

      - name: Set matrix
        id: set-matrix
        run: |
          if [[ $FILE_EXISTS == 'true' ]]; then
            echo "matrix=$(jq -c \
              --argjson with_coverage_flag "${{ inputs.with-coverage }}" \
              --arg minimum_php "${{ inputs.minimum-php }}" \
              --arg minimum_wp "${{ inputs.minimum-wp }}" \
              '
              .include |= (
                map(
                  # First, select only the versions that meet all minimum requirements
                  select(
                    (.php >= $minimum_php) and
                    (.wp == "latest" or .wp >= $minimum_wp)
                  ) |

                  # Next, update the coverage flag on the remaining items
                  if $with_coverage_flag == false and .coverage == true then
                    .coverage = false
                  else
                    .
                  end
                ) |

                # Finally, get the unique entries
                unique_by([.php, .os])
              )
              ' <<< "$BASE_MATRIX")" >> $GITHUB_OUTPUT
          else
            echo "matrix=" >> $GITHUB_OUTPUT
          fi
        env:
          BASE_MATRIX: ${{ needs.get-matrix.outputs.matrix }}
          FILE_EXISTS: ${{ steps.check_files.outputs.files_exists == 'true' }}

  unit:
    needs: prepare-unit
    if: ${{ needs.prepare-unit.outputs.matrix != '' }}
    name: Unit
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.prepare-unit.outputs.matrix) }}
    uses: ./.github/workflows/reusable-unit.yml
    secrets: inherit
    with:
      php: ${{ matrix.php }}
      coverage: ${{ matrix.coverage == true }}
      os: ${{ matrix.os || '' }}

  prepare-functional:
    name: Prepare matrix for functional tests
    needs: get-matrix
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Check out source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Check existence of composer.json & behat.yml files
        id: check_files
        run: echo "files_exists=$([ -f composer.json ] && [ -f behat.yml ] && echo true || echo false)" >> "$GITHUB_OUTPUT"

      - name: Set matrix
        id: set-matrix
        run: |
          if [[ $FILE_EXISTS == 'true' ]]; then
            echo "matrix=$(jq -c \
              --argjson with_coverage_flag "${{ inputs.with-coverage }}" \
              --arg minimum_php "${{ inputs.minimum-php }}" \
              --arg minimum_wp "${{ inputs.minimum-wp }}" \
              '
              # First, select only the versions that meet all minimum requirements
              .include |= (
                map(
                  select(
                    .php >= $minimum_php
                  ) |
                  # Next, update the coverage flag on the remaining items
                  if $with_coverage_flag == false and .coverage == true then
                    .coverage = false
                  else
                  .
                  end
                )
              ) |

              # Reassign WP4.9 to minimum_wp
              .include |= (
                map(
                  select(
                    .wp == "4.9"
                  ).wp |= $minimum_wp
                )
              )
              ' <<< "$BASE_MATRIX" )" >> $GITHUB_OUTPUT
          else
            echo "matrix=" >> $GITHUB_OUTPUT
          fi
        env:
          BASE_MATRIX: ${{ needs.get-matrix.outputs.matrix }}
          FILE_EXISTS: ${{ steps.check_files.outputs.files_exists == 'true' }}

  functional:
    needs: prepare-functional
    if: ${{ needs.prepare-functional.outputs.matrix != '' }}
    name: Behat
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.prepare-functional.outputs.matrix) }}
    uses: ./.github/workflows/reusable-functional.yml
    secrets: inherit
    with:
      php: ${{ matrix.php }}
      wp: ${{ matrix.wp }}
      dbtype: ${{ matrix.dbtype || 'mysql' }}
      mysql: ${{ matrix.mysql || '' }}
      object_cache: ${{ matrix.object_cache }}
      coverage: ${{ matrix.coverage == true }}
      os: ${{ matrix.os || '' }}
