name: Testing

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  test:
    uses: wp-cli/.github/.github/workflows/reusable-testing.yml@85be2d1b154ddf1b2f03166c93bc75a27fb3daf1
